# Generated by Django 4.1.3 on 2022-12-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_comments_comment_comments_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aloqa',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
